local listPokemon = 
{
['Ariados']=0,
['Beedrill']=0,
['Caterpie']=0,
['Doduo']=0,
['Ekans']=0,
['Furret']=2,
['Hoothoot']=2,
['Mankey']=0,
['Metapod']=0,
['Natu']=0,
['Nidoran F']=0,
['Nidoran M']=0,
['Noctowl']=0,
['Pidgey']=2,
['Pinsir']=0,
['Poliwag']=0,
['Ponyta']=2,
['Psyduck']=0,
['Rattata']=2,
['Sentret']=2,
['Shinx']=0,
['Silcoon']=0,
['Slowpoke']=0,
['Spearow']=0,
['Zubat']=2,
}
return listPokemon