local listPokemon = 
{
['Ariados']=0,
['Beedrill']=0,
['Caterpie']=0,
['Doduo']=2,
['Ekans']=0,
['Furret']=2,
['Hoothoot']=2,
['Mankey']=2,
['Metapod']=0,
['Natu']=2,
['Nidoran F']=2,
['Nidoran M']=2,
['Noctowl']=0,
['Pidgey']=2,
['Pinsir']=0,
['Poliwag']=2,
['Ponyta']=2,
['Psyduck']=0,
['Rattata']=2,
['Sentret']=2,
['Shinx']=0,
['Silcoon']=0,
['Slowpoke']=0,
['Spearow']=2,
['Zubat']=2,
}
return listPokemon