local listPokemon = 
{
['Arbok']=0,
['Aron']=0,
['Baltoy']=0,
['Beedrill']=0,
['Budew']=0,
['Butterfree']=0,
['Cascoon']=0,
['Caterpie']=2,
['Ekans']=0,
['Geodude']=0,
['Heracross']=0,
['Jigglypuff']=0,
['Kakuna']=2,
['Ledyba']=2,
['Metapod']=2,
['Nidoran M']=0,
['Noctowl']=2,
['Oddish']=0,
['Paras']=0,
['Pidgeotto']=0,
['Pidgey']=2,
['Pikachu']=0,
['Rhyhorn']=0,
['Sandshrew']=0,
['Sentret']=2,
['Shroomish']=0,
['Silcoon']=0,
['Snubbull']=2,
['Spinarak']=2,
['Venonat']=0,
['Weedle']=2,
['Yanma']=0,
}
return listPokemon