local listPokemon = 
{
['Arbok']=2,
['Aron']=0,
['Baltoy']=0,
['Beedrill']=2,
['Budew']=0,
['Butterfree']=2,
['Cascoon']=0,
['Caterpie']=2,
['Ekans']=0,
['Geodude']=0,
['Heracross']=0,
['Jigglypuff']=2,
['Kakuna']=2,
['Ledyba']=2,
['Metapod']=2,
['Nidoran M']=2,
['Noctowl']=2,
['Oddish']=2,
['Paras']=2,
['Pidgeotto']=2,
['Pidgey']=2,
['Pikachu']=2,
['Rhyhorn']=0,
['Sandshrew']=2,
['Sentret']=2,
['Shroomish']=0,
['Silcoon']=0,
['Snubbull']=2,
['Spinarak']=2,
['Venonat']=0,
['Weedle']=2,
['Yanma']=0,
}
return listPokemon