local listPokemon = 
{
['Arbok']=0,
['Aron']=0,
['Baltoy']=0,
['Beedrill']=0,
['Butterfree']=0,
['Caterpie']=2,
['Ekans']=0,
['Geodude']=0,
['Jigglypuff']=0,
['Kakuna']=2,
['Ledyba']=2,
['Mankey']=0,
['Metapod']=2,
['Nidoran F']=0,
['Nidoran M']=0,
['Noctowl']=2,
['Pidgey']=2,
['Rattata']=0,
['Rhyhorn']=0,
['Sandshrew']=0,
['Sentret']=2,
['Silcoon']=0,
['Snubbull']=2,
['Spearow']=0,
['Spinarak']=2,
['Venonat']=0,
['Weedle']=2,
['Yanma']=0,
['Zubat']=0,
}
return listPokemon